// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Repository.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;
using Entities.Models;
namespace Repository
{
    public partial class RepositoryContext
    {
        private IRepositoryContextProcedures _procedures;

        public virtual IRepositoryContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new RepositoryContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public IRepositoryContextProcedures GetProcedures()
        {
            return Procedures;
        }
    }

    public partial class RepositoryContextProcedures : IRepositoryContextProcedures
    {
        private readonly RepositoryContext _context;

        public RepositoryContextProcedures(RepositoryContext context)
        {
            _context = context;
        }

      
    }
}
