// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Repository.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;
using Entities.Models;
namespace Repository
{
    public partial class RepositoryContext
    {
        private IRepositoryContextProcedures _procedures;

        public virtual IRepositoryContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new RepositoryContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public IRepositoryContextProcedures GetProcedures()
        {
            return Procedures;
        }
    }

    public partial class RepositoryContextProcedures : IRepositoryContextProcedures
    {
        private readonly RepositoryContext _context;

        public RepositoryContextProcedures(RepositoryContext context)
        {
            _context = context;
        }
        public virtual async Task<int> USP_FillDLLAsync(string tableName, string textField, string valueField, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new[]
            {
                new SqlParameter
                {
                    ParameterName = "TableName",
                    Size = 256,
                    Value = tableName ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "TextField",
                    Size = 256,
                    Value = textField ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "ValueField",
                    Size = 256,
                    Value = valueField ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[USP_FillDLL] @TableName = @TableName, @TextField = @TextField, @ValueField = @ValueField", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

       
    }
}
