// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entities.Models;

public partial class MBank
{
    public string BankCode { get; set; }

    public string BankCodeShort { get; set; }

    public string BankName { get; set; }

    public decimal? SlTypeId { get; set; }

    public string CenterCode { get; set; }

    public string BankAccountNo { get; set; }

    public string BankAddress { get; set; }

    public string Usernm { get; set; }

    public DateTime? TransDt { get; set; }

    public string InFavourOf { get; set; }

    public string SalAccount { get; set; }

    public string Bcode { get; set; }

    public string AccountType { get; set; }

    public string CompanyCode { get; set; }

    public string LocationCode { get; set; }

    public string Volume { get; set; }

    public string IfscCode { get; set; }

    public string Branch { get; set; }
}