// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entities.Models;

public partial class MCDesg
{
    public string Ccode { get; set; }

    public string DesigCatDesc { get; set; }

    public decimal? SavingContrubution { get; set; }

    public decimal? DoubleAccidentalPremium { get; set; }

    public int? CreatedBy { get; set; }

    public DateOnly? CreatedDate { get; set; }

    public int? UpdatedBy { get; set; }

    public DateOnly? UpdatedDate { get; set; }
}