// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entities.Models;

public partial class MCity
{
    public Guid? CityId { get; set; }

    public decimal CityId1 { get; set; }

    public string CityName { get; set; }

    public string Stdcode { get; set; }

    public string StateId { get; set; }

    public decimal? StateId1 { get; set; }

    public string RecFlag { get; set; }

    public string UserNm { get; set; }

    public DateTime? TransDt { get; set; }
}