// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entities.Models;

public partial class MCompany
{
    public long TableId { get; set; }

    public string CompCode { get; set; }

    public string CompanyDesc { get; set; }

    public DateTime? Cdate { get; set; }

    public string CompanyAddress { get; set; }

    public string Tanno { get; set; }

    public string Panno { get; set; }

    public string Pin { get; set; }
}