// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entities.Models;

public partial class MDepartment
{
    public int TableId { get; set; }

    public string DepartmentCode { get; set; }

    public string DepartmentName { get; set; }

    public string CreatedBy { get; set; }

    public DateOnly? CreatedDate { get; set; }

    public string UpdatedBy { get; set; }

    public DateOnly? UpdatedDate { get; set; }
}