// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entities.Models;

public partial class MDesignationMast
{
    public int TableId { get; set; }

    public string DepttCode { get; set; }

    public string DesigCode { get; set; }

    public string DesigDesc { get; set; }

    public string PayGrade { get; set; }

    public string CadreCode { get; set; }

    public string EstCat { get; set; }

    public string EmpGenDesc { get; set; }

    public string EmpGenCd { get; set; }

    public string Ccode { get; set; }

    public string Payscale { get; set; }

    public int? OrderNumber { get; set; }

    public string DesigHindi { get; set; }
}