// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entities.Models;

public partial class MEmpMast
{
    public string Ecode { get; set; }

    public string EmpName { get; set; }

    public string FathName { get; set; }

    public DateOnly? DateOfBirth { get; set; }

    public string Qualification { get; set; }

    public string Sex { get; set; }

    public string MaritalStatus { get; set; }

    public string LocAdd1 { get; set; }

    public string LocAdd2 { get; set; }

    public string LocAdd3 { get; set; }

    public string ParAdd1 { get; set; }

    public string ParAdd2 { get; set; }

    public string ParAdd3 { get; set; }

    public string HomeTown { get; set; }

    public decimal? NoOfChild { get; set; }

    public string WifeGovtSerFlag { get; set; }

    public string Grp { get; set; }

    public string Section { get; set; }

    public DateOnly? DateOfJoin { get; set; }

    public DateOnly? ConfirmDate { get; set; }

    public DateOnly? RetireDate { get; set; }

    public DateOnly? ActualRetireDate { get; set; }

    public DateOnly? DateOfIncrement { get; set; }

    public string PayGrade { get; set; }

    public decimal? Basic { get; set; }

    public decimal? PersonalPay { get; set; }

    public decimal? SpecialPay { get; set; }

    public string ModeSalPay { get; set; }

    public string BankName { get; set; }

    public string AcctNo { get; set; }

    public string GovtAccFlag { get; set; }

    public string OffVechFlag { get; set; }

    public string SpecialAllowance { get; set; }

    public string WashAllFlag { get; set; }

    public string ChildAllFlag { get; set; }

    public string PayReleaseFlag { get; set; }

    public string HandicaptFlag { get; set; }

    public decimal? GpfDed { get; set; }

    public decimal? CdtAmt { get; set; }

    public decimal? IncomeTax { get; set; }

    public string ProfessionFlag { get; set; }

    public string EmpStatus { get; set; }

    public decimal? AppDoptiiNo { get; set; }

    public decimal? ConfDoptiiNo { get; set; }

    public decimal? LevDoptiiNo { get; set; }

    public DateOnly? DtNxIncr { get; set; }

    public string NearRailStation { get; set; }

    public string BirthPlace { get; set; }

    public string DesigCode { get; set; }

    public string RetYear { get; set; }

    public string QStatus { get; set; }

    public string PfNo { get; set; }

    public string TNo { get; set; }

    public string Subject { get; set; }

    public string Univ { get; set; }

    public string Qalific1 { get; set; }

    public string Qalific2 { get; set; }

    public string Qalific3 { get; set; }

    public string Qalific4 { get; set; }

    public DateOnly? DtGovt { get; set; }

    public string ProRec { get; set; }

    public DateOnly? DtPmt { get; set; }

    public string ScSt { get; set; }

    public string ResPhone { get; set; }

    public string PhoneNo { get; set; }

    public string BloodGp { get; set; }

    public string ReliefFlag { get; set; }

    public string DeathSchFlag { get; set; }

    public string MiscFlag { get; set; }

    public string Medico { get; set; }

    public string AccoCode { get; set; }

    public string Busflag { get; set; }

    public string VCode { get; set; }

    public string EstCode { get; set; }

    public string WifeSerFlag { get; set; }

    public string WifeEcode { get; set; }

    public decimal? CatCode { get; set; }

    public decimal? Promotion { get; set; }

    public string OrderNo { get; set; }

    public string Recflag { get; set; }

    public string DepType { get; set; }

    public string DepttCode { get; set; }

    public string BgtCatCode { get; set; }

    public string BankCode { get; set; }

    public string PanNo { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public decimal? GradePay { get; set; }

    public string SalOldNewFlag { get; set; }

    public decimal? LocPin { get; set; }

    public decimal? ParPin { get; set; }

    public string LocState { get; set; }

    public string ParState { get; set; }

    public string ExTelNo { get; set; }

    public decimal? GisDed { get; set; }

    public string GpfType { get; set; }

    public string Tecode { get; set; }

    public string CreatedBy { get; set; }

    public DateOnly? CreatedDate { get; set; }

    public string UpdatedBy { get; set; }

    public DateOnly? UpdatedDate { get; set; }

    public string CentreCode { get; set; }

    public string LastCentreCode { get; set; }

    public string Dhraflag { get; set; }

    public string Remark { get; set; }

    public string Caste { get; set; }

    public int? Sflag { get; set; }

    public string Gslip { get; set; }

    /// <summary>
    /// 0= Uncheked and 1= cheked
    /// </summary>
    public int? Hraflag { get; set; }

    public string CompanyName { get; set; }

    public string EmpType { get; set; }

    public string LocDistrict { get; set; }

    public string ParDistrict { get; set; }

    public string EmpClass { get; set; }

    public string SubCasteCatg { get; set; }

    public string CurPayGrade { get; set; }

    public string PayBand { get; set; }

    public string Da { get; set; }

    public string RateDa { get; set; }

    public string EmpContribution { get; set; }

    public string MediAllow { get; set; }

    public string CityAllow { get; set; }

    public string DesigCat { get; set; }

    public string PayRev { get; set; }

    public string GpfCpfNo { get; set; }

    public string DepuLocation { get; set; }

    public string MobileNo { get; set; }

    public string SpouseJobLocation { get; set; }

    public string EmpCodeOld { get; set; }

    public string EStation { get; set; }

    public string EDesg { get; set; }

    public string EGrade { get; set; }

    public string EScale { get; set; }

    public string JoiningLocation { get; set; }

    public DateTime? AppointmentDate { get; set; }

    public string AppointmentOrderNo { get; set; }

    public string RemarkDeputation { get; set; }

    public string InoutdeputationType { get; set; }

    public string InoutdeputationLocName { get; set; }

    public string AadharNumber { get; set; }

    public string EmployeeClass { get; set; }

    public string NameHindi { get; set; }
}