// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entities.Models;

public partial class MEmpMastAddDetail
{
    public string Ecode { get; set; }

    public string SpouseJobLocation { get; set; }

    public string ImagePath { get; set; }

    public string LocAdd { get; set; }

    public string LocDistrict { get; set; }

    public string LocState { get; set; }

    public string LocContact { get; set; }

    public decimal? LocPin { get; set; }

    public string ExTelNo { get; set; }

    public string ParAdd { get; set; }

    public string HomeTown { get; set; }

    public string PerRailway { get; set; }

    public string PerPan { get; set; }

    public string ParDistrict { get; set; }

    public string ParEmail { get; set; }

    public string ParState { get; set; }

    public string ParMobile { get; set; }

    public string ParPhn { get; set; }

    public decimal? ParPin { get; set; }

    public string QualType { get; set; }

    public string AcQual { get; set; }

    public string AcYear { get; set; }

    public string AcRemark { get; set; }

    public string PfQual { get; set; }

    public string PfYear { get; set; }

    public string PfRemark { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? RowId { get; set; }

    public string PersonalIdmark { get; set; }
}