// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entities.Models;

public partial class MFamilyDetail
{
    public string Ecode { get; set; }

    public string PersonName { get; set; }

    public int RowId { get; set; }

    public int? RelationWithEmp { get; set; }

    public string Sex { get; set; }

    public string PersonStatus { get; set; }

    public DateOnly? Dob { get; set; }

    public string Dependent { get; set; }

    public string CreatedBy { get; set; }

    public DateOnly? CreatedDate { get; set; }

    public string UpdatedBy { get; set; }

    public DateOnly? UpdatedDate { get; set; }

    public int? Status { get; set; }
}