// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entities.Models;

public partial class MNominee
{
    public string Ecode { get; set; }

    public int RowId { get; set; }

    public string NomineeName { get; set; }

    public DateOnly? NominationDt { get; set; }

    public string Add1 { get; set; }

    public string Add2 { get; set; }

    public string Add3 { get; set; }

    public string RelationWithEmp { get; set; }

    public string MaritalStatus { get; set; }

    public string NominationFor { get; set; }

    public decimal? AmtPercent { get; set; }

    public string Contigencies { get; set; }

    public string NxNominee { get; set; }

    public string NxAdd1 { get; set; }

    public string NxAdd2 { get; set; }

    public string NxAdd3 { get; set; }

    public string NxRelationWithEmp { get; set; }

    public string NxMaritalStatus { get; set; }

    public string NomineeStatus { get; set; }

    public string NxNomineeStatus { get; set; }

    public DateOnly? Dob { get; set; }

    public DateOnly? NxDob { get; set; }

    public int? CreatedBy { get; set; }

    public DateOnly? CreatedDate { get; set; }

    public int? UpdatedBy { get; set; }

    public DateOnly? UpdatedDate { get; set; }
}