// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Entities.Models
{
    public partial class sp_OrganisationResult
    {
        public int TableID { get; set; }
        [StringLength(128)]
        public string Name { get; set; }
        [StringLength(8)]
        public string SHName { get; set; }
        [StringLength(64)]
        public string CEOName { get; set; }
        [StringLength(64)]
        public string Contact { get; set; }
        [StringLength(16)]
        public string RegistrationNum { get; set; }
        public DateTime? RegistrationDt { get; set; }
        [StringLength(10)]
        public string PAN { get; set; }
        [StringLength(150)]
        public string Address { get; set; }
        [StringLength(50)]
        public string Phone { get; set; }
        [StringLength(50)]
        public string Mobile { get; set; }
        [StringLength(100)]
        public string Email { get; set; }
        public string SelfFlag { get; set; }
        [StringLength(250)]
        public string Logo { get; set; }
        [StringLength(500)]
        public string LogoName { get; set; }
        [StringLength(32)]
        public string CreatedBy { get; set; }
        public DateTime CreatedDate { get; set; }
        [StringLength(32)]
        public string UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }
        [StringLength(20)]
        public string fax { get; set; }
        [StringLength(50)]
        public string website { get; set; }
    }
}
